---
kind: pipeline
type: docker
name: test

environment:
  MYVAR: "hello world"

steps:
- name: "test"
  image: alpine
  commands:
    - "ls -la"
    - "echo $MYVAR $MYVAR2"
    - sleep 20
  environment:
    MYVAR2: "test test"

